# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
locals {
  environment = terraform.workspace
  default_tags = {
     contact = "wlewalski@lexisnexisrisk.com"
     environment = terraform.workspace
     location = var.location
     terraform = true
  }
}
