# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">= 1.1.0"
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "lexis-test"
    workspaces {
     prefix = "waylew-aks-network-"
    }
}
}
