# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
   terraform {
    backend "remote" {
    hostname = "app.terraform.io"
    organization = "lexis-test"
    workspaces {
     prefix = "my-aks-resource-group-"
    }
  }
}
