name: validate terraform

on:
  pull_request:
    branches: [main]
    paths:
      - "terraform/**.tf"

  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./terraform

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Init TFLint
        run: tflint --init
      - name: Run TFLint
        run: tflint -f compact
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          framework: terraform


